spring.application.name=Buchverwaltung
spring.datasource.url=jdbc:mysql://localhost:3306/buchverwaltung
spring.datasource.username=root
spring.datasource.password=MeinMysql123!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true